# Generated by Django 6.0.6 on 2026-06-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
