# Generated by Django 6.0.6 on 2026-07-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventteam',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('lead', 'Lead')], default='volunteer', max_length=20),
        ),
    ]
