# Generated by Django 6.0.6 on 2026-06-22 07:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_cancellation_reason_event_rejection_reason'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'event')},
        ),
    ]
